# Generated by Django 4.0.5 on 2022-06-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/quizz')),
                ('topic', models.CharField(max_length=120, null=True)),
                ('time', models.FloatField(help_text='duration time by minutes', null=True)),
                ('max_score', models.PositiveBigIntegerField()),
                ('type', models.CharField(choices=[('easy', 'easy'), ('normal', 'normal'), ('expert', 'expert')], default='easy', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'quizes',
            },
        ),
    ]
